AWSTemplateFormatVersion: 2010-09-09

Description: Reference Architecture to host a CF Name. Designed to be launched in eu-west2. 

Metadata:
  Author: Reyan Ahmed
  Email: aws.reyan@gmail.com

#----------------------------------------------------------------
AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: VPC Configuration
      Parameters:
      - NumberOfAZs
      - AvailabilityZones
      - VpcCidr
      - VpcTenancy
      - PublicSubnet1Cidr
      - PublicSubnet2Cidr
      - PublicSubnet3Cidr
      - PrivateSubnet1Cidr
      - PrivateSubnet2Cidr
      - PrivateSubnet3Cidr
    - Label:
        default: Web Application
      Parameters: 
      - EC2KeyPair
      - InstanceType
      - ElasticIpId
      - EIPAssociation
      - AMI
      - InstanceSecurityGroup
      - InstanceSubnet
    - Label:
        default: RDS Backend
      Parameters:
      - DbInstanceType
      - DbMasterUsername
      - DbMasterPassword
      - DatabaseName
      - DatabaseEncryption
      - DatabaseCMK
      - DatabaseSecurityGroup
      - DbNumberOfSubnets
      - Subnet

#----------------------------------------------------------------
    ParameterLabels:
      #VPC Parameter Labels
      NumberOfAZs:
        default: Number of Availability Zones
      AvailabilityZones:
        default: Availability Zones
      PublicSubnet1Cidr:
        default: Public Subnet 1
      PublicSubnet2Cidr:
        default: Public Subnet 2
      PublicSubnet3Cidr:
        default: Public Subnet 3
      PrivateSubnet1Cidr:
        default: Private Subnet 1 
      PrivateSubnet2Cidr:
        default: Private Subnet 2
      PrivateSubnet3Cidr:
        default: Private Subnet 3
      #EC2 Parameter Labels
      EC2KeyPair:
        default: EC2 Key Pair
      InstanceType:
        default: Instance Type
      EIPAssociation:
        default: EIP Association
      AMI:
        default: Select AMI
      #RDS Parameter Labels
      DbInstanceType:
        default: DB Instance Engine
      DbMasterUsername:
        default: DB Master Username
      DbMasterPassword:
        default: DB Master Password
      DatabaseName: 
        default: Database Name
      DatabaseEncryption:
        default: Database Encryption Type
      DatabaseCMK:
        default: AWS-KMS Customer Master Key
      DatabaseSecurityGroup:
        default: Database Security Group
      DbNumberOfSubnets:
        default: Number of Subnets
      Subnet:
        default: Subnets

#----------------------------------------------------------------
Parameters:
  #VPC Parameters
  NumberOfAZs:
    AllowedValues:
    - 2
    - 3
    Default: 2
    Description: Select Number of Availability Zones to use in the VPC. Must match your
      selections in the list of Availability Zones.
    Type: Number
  AvailabilityZones:
    Description: 'Select from List of Availability Zones to use for the subnets in this VPC.'
    Type: List<AWS::EC2::AvailabilityZone::Name>
  VpcCidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: Enter CIDR block for the VPC
    Type: String
  VpcTenancy:
    AllowedValues:
    - default
    - dedicated
    Default: default
    Description: Select Tenancy to launch VPC in
    Type: String
  EnvironmentTags:
    AllowedValues:
    - Development
    - Testing
    - Production
    Default: Development
    Description: Select Name Environment
    Type: String

  #VPCSubnetParameters
  PublicSubnet1Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.201.0/24
    Description: CIDR block for Public subnet 1 located in Availability Zone 1
    Type: String
  PublicSubnet2Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.202.0/24
    Description: CIDR block for Public subnet 2 located in Availability Zone 2
    Type: String
  PublicSubnet3Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.203.0/24
    Description: CIDR block for Public subnet 3 located in Availability Zone 3
    Type: String
  PrivateSubnet1Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.100.0/24
    Description: CIDR block for data subnet 0 located in Availability Zone 0
    Type: String
  PrivateSubnet2Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.101.0/24
    Description: CIDR block for data subnet 1 located in Availability Zone 1
    Type: String
  PrivateSubnet3Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.102.0/24
    Description: CIDR block for data subnet 2 located in Availability Zone 2
    Type: String

  #EC2 Parameters
  InstanceType:
    Default: t2.micro
    Description: Select Instance Type
    Type: String
  EIPAssociation:
    Description: Select EIP ID to associate
    Type: String
  AMI:
    Description: Select AMI to use
    Type: String
    Default: ami-08ca3fed11864d6bb
  
  #RDS Parameters
    DbInstanceType:
      Description: Enter Database Instance Class
      Type: String
      Default: db.t3.micro
    DbMasterUsername:
      AllowedPattern: ^([a-zA-Z0-9]*)$
      Description: Enter RDS master username
      ConstraintDescription: Must contain only alphanumeric characters (minimum 8; maximum 16).
      MaxLength: 16
      MinLength: 8
      Type: String
    DbMasterPassword:
      AllowedPattern: ^([a-z0-9A-Z`~!#$%^&*()_+,\\-])*$
      ConstraintDescription: Must have letters, numbers and at least one of the following characters '_'`~!#$%^&*()_+,-    
      Description: RDS master password.
      MaxLength: 41
      MinLength: 8
      NoEcho: true
      Type: String
    DatabaseName:
      AllowedPattern: ^([a-zA-Z0-9]*)$
      Description: RDS master database name
      Type: String
    DatabaseEncryption:
      AllowedValues:
        - true
        - false
      Default: True
      Description: Indicates whether the DB instances in the cluster are encrypted
      Type: String
    DatabaseCMK:
      Description: AWS KMS Customer Master Key (CMK) to encrypt database cluster
      Type: String

  
#----------------------------------------------------------------
Conditions:

  AvailableAWSRegion: !Equals [ !Ref 'AWS::Region', eu-west-2]

  
#----------------------------------------------------------------
Resources:

  MasterVpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        NumberOfAZs:
          !Ref NumberOfAZs
        AvailabilityZones:
          !Join
            - ','
            - !Ref AvailabilityZones        
        VpcCidr:
          !Ref VpcCidr
        VpcTenancy:
          !Ref VpcTenancy
        PublicSubnet1Cidr:
          !Ref PublicSubnet1Cidr
        PublicSubnet2Cidr:
          !Ref PublicSubnet2Cidr
        PublicSubnet3Cidr:
          !Ref PublicSubnet3Cidr
        PrivateSubnet1Cidr:
          !Ref PrivateSubnet1Cidr
        PrivateSubnet2Cidr:
          !Ref PrivateSubnet2Cidr
        PrivateSubnet3Cidr:
          !Ref PrivateSubnet3Cidr
      TemplateURL: #//TODO:

  MasterRDS:
    Condition: AvailableAWSRegion
    DependsOn: [ MasterVpc, MasterSecurityGroups ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DbInstanceType:
          !Ref DbInstanceType
        DbMasterUsername:
          !Ref DbMasterUsername
        DbMasterPassword:
          !Ref DbMasterPassword
        DatabaseName:
          !Ref DatabaseName
        DatabaseEncryption:
          !Ref DatabaseEncryption
        DatabaseCMK:
          !Ref DatabaseCMK
        DatabaseSecurityGroup:
          !GetAtt [ MasterSecurityGroups, Outputs.DatabaseSecurityGroup ] #//TODO:
        DbNumberOfSubnets:
          !Ref NumberOfAZs
        Subnet:
          !GetAtt [ MasterVpc, Outputs.PrivateSubnet ] #//TODO:
      TemplateURL: url.yaml #//TODO:

  MasterApp:
    Condition: AvailableAWSRegion
    DependsOn: [ MasterVpc, MasterSecurityGroups ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EC2KeyPair:
          !Ref EC2KeyPair
        InstanceType:
          !Ref InstanceType
        AMI:
          !Ref AMI
        InstanceSecurityGroup:
          !GetAtt [ MasterSecurityGroups, Outputs.AppSecurityGroup ]
        InstanceSubnet:
          !GetAtt [ MasterVpc, Outputs.PublicSubnet ]
      TemplateURL: #TODO:



  MasterSecurityGroups: #//TODO: